language: java

jdk:
  - openjdk8

addons:
  sonarcloud:
    organization: "thomashan-github"

script:
  - ./gradlew --scan build sonarqube jacocoTestReport coveralls

after_success:
  - bash <(curl -s https://codecov.io/bash)
